apiVersion: coredns.mandelsoft.org/v1alpha1
kind: CoreDNSEntry
metadata:
  name: (( values.dns.name ))
  namespace: (( values.dns.namespace ))

  labels:
    target: dataplane
    app: (( values.runtime.label ))
spec:
  zoneRef: nameserver
  dnsNames: (( values.dns.dnsnames ))
  A: (( values.dns.ips || ~~ ))
  CNAME: (( values.dns.cname || ~~ ))