helper:
  <<<: (( &temporary ))
  secret:
    mount:
      name: secret-volume
      mountPath: /etc/coredns # Mount point for the config file
      readOnly: true
    volume:
      - name: secret-volume
        secret:
          secretName: (( values.config.name )) # Must match the ConfigMap name above
          items:
            - key: KubeConfig # Key in the ConfigMap
              path: KubeConfig # Filename inside the mountPath

apiVersion: apps/v1
kind: Deployment
metadata:
  name: (( values.deployment.name ))
  namespace: (( values.runtime.namespace ))

  labels:
    target: runtime
    app: (( values.deployment.label ))
spec:
  replicas: (( values.deployment.replicas ))
  selector:
    matchLabels:
      app: (( values.deployment.label ))
  template:
    metadata:
      labels:
        app: (( values.deployment.label ))
    spec:
      automountServiceAccountToken: (( optional(! values.runtime.separated, false) ))
      serviceAccountName: (( optional( ! values.runtime.separated || true, values.deployment.name) ))
      containers:
        - name: dns-container
          # Use your actual image here. Using coredns/coredns as an example.
          image: coredns/coredns:latest
          imagePullPolicy: IfNotPresent

          # Pass the config file path via the --corefile option
          args:
            - -conf
            - /etc/coredns/Corefile # Path to the mounted config file

          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP

          volumeMounts:
            - <<<: (( optional(values.runtime.separated, helper.secret.mount) ))
            - name: config-volume
              mountPath: /etc/coredns # Mount point for the config file
              readOnly: true


      volumes:
        - <<<: (( optional(values.runtime.separated, helper.secret.volume) ))
        - name: config-volume
          secret:
            secretName: (( values.config.name )) # Must match the ConfigMap name above
            items:
              - key: Corefile # Key in the ConfigMap
                path: Corefile # Filename inside the mountPath