
apiVersion: v1
kind: ServiceAccount
metadata:
  name: (( values.deployment.name ))
  namespace: (( values.dataplane.namespace ))
  labels:
    target: dataplane
    app: (( values.deployment.label ))