apiVersion: coredns.mandelsoft.org/v1alpha1
kind: HostedZone
metadata:
  labels:
    app.kubernetes.io/name: kubedns
    app.kubernetes.io/managed-by: kustomize
  name: hostedzone-sample
spec:
  # TODO(user): Add fields here
