kind: ConfigMap
apiVersion: v1
metadata:
  name: (( values.runtime.name ))
  namespace: (( values.runtime.namespace ))
  labels:
    target: runtime
    app: (( values.runtime.label ))
data:
  Corefile: (( values.runtime.corefile ))