helper:
  <<<: (( &temporary ))
  secret:
    mount:
      - name: secret-volume
        mountPath: /etc/coredns/access
        readOnly: true
    volume:
      - name: secret-volume
        secret:
          secretName: (( values.runtime.secret.name )) # Must match the secret name
          items:
            - key: token # Key in the ConfigMap
              path: token # Filename inside the mountPath
            - key: ca.crt # Key in the ConfigMap
              path: ca.crt # Filename inside the mountPath
########################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: (( values.runtime.name ))
  namespace: (( values.runtime.namespace ))

  labels:
    target: runtime
    app: (( values.runtime.label ))
spec:
  replicas: (( values.runtime.replicas ))
  selector:
    matchLabels:
      app: (( values.runtime.label ))
  template:
    metadata:
      labels:
        app: (( values.runtime.label ))
    spec:
      automountServiceAccountToken: (( values.runtime.secret.name == "" ))
      serviceAccountName: (( optional( values.runtime.secret.name == "", values.runtime.name) ))
      containers:
        - name: dns-container
          # Use your actual image here. Using coredns/coredns as an example.
          image: mandelsoft/coredns:latest
          imagePullPolicy: Always

          # Pass the config file path via the --corefile option
          args:
            - -conf
            - /etc/coredns/config/Corefile # Path to the mounted config file

          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP

          volumeMounts:
            - <<<: (( optional(values.runtime.secret.name != "", helper.secret.mount) ))
            - name: config-volume
              mountPath: /etc/coredns/config # Mount point for the config file
              readOnly: true


      volumes:
        - <<<: (( optional(values.runtime.secret.name != "", helper.secret.volume) ))
        - name: config-volume
          configMap:
            name: (( values.runtime.name )) # Must match the ConfigMap name above
            items:
              - key: Corefile # Key in the ConfigMap
                path: Corefile # Filename inside the mountPath