
resource:
  <<<: (( &temporary ))
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: (( values.dataplane.name ))
    namespace: (( values.dataplane.namespace ))
    labels:
      target: dataplane
      app: (( values.dataplane.label ))

manifest: (( optional(values.dataplane.required, resource) ))