apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: dns-service-nameserver
  name: dns-service-nameserver
  namespace: dns-system
data:
  Corefile: |-
    .:53 {
      errors
      health
      ready
      cache 30
      kubedyndns . {
        mode Primary
        zoneobject nameserver
        namespaces dns-system
        endpoint https://api.dns-api.mandelsoft.shoot.canary.k8s-hana.ondemand.com
        token /etc/coredns/access/token /etc/coredns/access/ca.crt
        ttl 30
      }
    }
