apiVersion: v1
kind: Namespace
metadata:
  name: dns-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiexport-access-coredns
rules:
- apiGroups: ["apis.kcp.io"]
  resources: ["apiexports/content"]
  resourceNames: ["coredns.mandelsoft.org"]
  verbs: ["get","list","watch","update","patch","delete"]
- apiGroups: ["apis.kcp.io"]
  resources: ["apibindings"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apis.kcp.io"]
  resources: ["apiexportendpointslices"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiexport-access-coredns
subjects:
- kind: ServiceAccount
  name: apiexport-serviceaccount-coredns
  namespace: dns-service
roleRef:
  kind: ClusterRole
  name: apiexport-access-coredns
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiexport-serviceaccount-coredns
  namespace: dns-service
---
apiVersion: v1
kind: Secret
metadata:
  name: kcp-controller-token
  namespace: dns-service
  annotations:
    kubernetes.io/service-account.name: apiexport-serviceaccount-coredns
type: kubernetes.io/service-account-token
