package hostedzone

import (
	"context"
	errors2 "errors"
	"fmt"
	"net"
	"reflect"

	"github.com/go-test/deep"
	corednsv1alpha1 "github.com/mandelsoft/kubedns/api/coredns/v1alpha1"
	"github.com/mandelsoft/kubedns/pkg/clusterutils"
	"github.com/mandelsoft/kubedns/pkg/owner"
	"github.com/mandelsoft/kubedns/pkg/render"
	"github.com/mandelsoft/logging"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/serializer/yaml"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
)

const GENERATED = "!!! DO NOT CHANGE MANUALLY, THIS OBJECT IS AUTOMATICALLY GENERATED BY THE HostedZOne CONTROLLER."

type ReconcileRequest struct {
	ReconcileContext
	reconciler *HostedZoneReconciler
	instance   *corednsv1alpha1.HostedZone
	orig       *corednsv1alpha1.HostedZone
}

var _ clusterutils.OperationContext = (*ReconcileRequest)(nil)

func NewRequest(ctx context.Context, l logging.Logger, reconciler *HostedZoneReconciler, key client.ObjectKey, instance *corednsv1alpha1.HostedZone) *ReconcileRequest {
	return &ReconcileRequest{
		ReconcileContext: NewReconcileContext(ctx, l, reconciler.DataPlaneURL, reconciler.Options.IaaS, key),
		reconciler:       reconciler,
		orig:             instance,
		instance:         instance.DeepCopy(),
	}
}

func (r *ReconcileRequest) Reconcile() error {
	obj := r.instance
	// prepare finalizer update
	patch := client.MergeFrom(r.orig)

	// check responsibility
	ok, root, err := r.IsResponsibileFor()
	if !ok || err != nil {
		if !ok {
			r.Info("not responsible for this zone")
		}
		return err
	}
	r.Info("have to handle object")

	if r.ChangedResponsibility() || !obj.ObjectMeta.DeletionTimestamp.IsZero() {
		// Handle Deletion
		if obj == nil || !obj.ObjectMeta.DeletionTimestamp.IsZero() {
			r.Info("deletion of object requested")
		} else {
			r.Info("responsibility changed", "parent", obj.Spec.ParentRef, "runtime", obj.Spec.Runtime, "class", obj.Spec.Class)
		}
		if obj == nil || controllerutil.ContainsFinalizer(obj, r.reconciler.Finalizer) {
			if obj == nil {
				r.Info("object vanished -> cleanup pending resources")
			} else {
				r.Info("already active -> delete dependent resources")
			}
			// Run your external cleanup logic here
			if err := r.DeleteExternalResources(); err != nil {
				// If cleanup fails, we don't remove the finalizer;
				// we requeue to try again.
				return err
			}

			if obj != nil {
				// Remove finalizer and update
				r.Info("finally removing finalizer")
				if controllerutil.RemoveFinalizer(obj, r.reconciler.Finalizer) {
					if err := r.reconciler.DataPlane.Patch(r, obj, patch); err != nil {
						return client.IgnoreNotFound(err)
					}
				}
				return nil
			}
		}

		// Stop reconciliation as the item is being deleted
		return nil
	}

	// handle finalizer
	if obj.Spec.ParentRef != "" {
		// Remove finalizer from slave and update
		r.Info("removing finalizer for slave zone")
		if controllerutil.RemoveFinalizer(obj, r.reconciler.Finalizer) {
			if err := r.reconciler.DataPlane.Patch(r, obj, patch); err != nil {
				return client.IgnoreNotFound(err)
			}
		}
	} else {
		if controllerutil.AddFinalizer(obj, r.reconciler.Finalizer) {
			if err := r.reconciler.DataPlane.Patch(r, obj, patch); err != nil {
				return client.IgnoreNotFound(err)
			}
			r.Info("taking responsibilty")
		}
	}

	//  Normal Business Logic
	r.Info("handle hosted zone")
	return r.handleObject(root)
}

func (r *ReconcileRequest) GetFieldManager() string {
	return r.reconciler.FieldManager
}

func (r *ReconcileRequest) Modify(obj client.Object) error {
	return nil
}

func (r *ReconcileRequest) ChangedResponsibility() bool {
	obj := r.instance
	if obj == nil {
		// enforced object deletion
		return true
	}
	if !controllerutil.ContainsFinalizer(obj, r.reconciler.Finalizer) {
		return false
	}
	if obj.Spec.ParentRef != "" {
		// zone has been moved and is no top-level zone anymore
		return true
	}
	if obj.Status.Observed == nil {
		// never handled
		return false
	}
	if obj.Status.Observed.Runtime != String(obj.Spec.Runtime, "") || obj.Status.Observed.Class != String(obj.Spec.Class, "") {
		// responsibility change has been requested
		return true
	}
	return false
}

func (r *ReconcileRequest) IsResponsibileFor() (bool, *Responsibility, error) {
	obj := r.instance
	if obj == nil {
		return true, nil, nil
	}
	if controllerutil.ContainsFinalizer(obj, r.reconciler.Finalizer) {
		return true, nil, nil
	}
	r.Info("lookup root")
	info, ok, err := r.reconciler.GetRootInfo(r, r, obj)
	if err != nil {
		if ok {
			// dangling object, always report problem
			r.Info("report dangling zone", "error", err.Error())
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.ValidationConditionType,
				Status:  metav1.ConditionFalse, // Use metav1 constant
				Reason:  corednsv1alpha1.ReasonInvalidParent,
				Message: err.Error(),
			})
			err = nil
		}
		return false, nil, err
	}
	new := info.Runtime == r.reconciler.Options.Runtime && info.Class == r.reconciler.Options.Class
	r.Info("checking match", "root", info.Root.Name, "match", new, "runtime", info.Runtime, "class", info.Class)
	if info.Root.Status.Observed == nil {
		return new, info, nil
	}

	match := info.Root.Status.Observed.Class == r.reconciler.Options.Class && info.Root.Status.Observed.Class == r.reconciler.Options.Class
	r.Info("checking registered match", "root", info.Root.Name, "match", new, "runtime", info.Root.Status.Observed.Runtime, "class", info.Root.Status.Observed.Class)
	return match, info, nil

}

func (r *ReconcileRequest) handleObject(root *Responsibility) error {
	reason, err := r.Validate()
	if err != nil {
		if reason != "" {
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.ValidationConditionType,
				Status:  metav1.ConditionFalse, // Use metav1 constant
				Reason:  reason,
				Message: err.Error(),
			})
		}
		return err
	}

	var observed *corednsv1alpha1.Observed
	if r.instance.Spec.ParentRef == "" {
		observed = r.instance.Status.Observed
		if observed == nil {
			r.Logger.Info("registering responsibility")
			observed = &corednsv1alpha1.Observed{
				Runtime: r.reconciler.Options.Runtime,
				Class:   r.reconciler.Options.Class,
			}
		}
	}

	r.Logger.Info("validation succeeded")
	// --- Validation Succeeded: Use meta.SetStatusCondition to set ConditionTrue ---
	r.SetStatusCondition(metav1.Condition{
		Type:    corednsv1alpha1.ValidationConditionType,
		Status:  metav1.ConditionTrue,
		Reason:  reason,
		Message: "The HostedZone specification passed all validation checks.",
	})
	SetPointerField(&r.instance.Status.Observed, observed)

	if r.instance.Spec.ParentRef != "" {
		// update status from root
		for _, c := range root.Root.Status.Conditions {
			if c.Type != corednsv1alpha1.ValidationConditionType {
				r.SetStatusCondition(metav1.Condition{
					Type:    c.Type,
					Status:  c.Status,
					Reason:  c.Reason,
					Message: c.Message,
				})
			}
		}
		for _, c := range r.instance.Status.Conditions {
			if meta.FindStatusCondition(root.Root.Status.Conditions, c.Type) != nil {
				meta.RemoveStatusCondition(&r.instance.Status.Conditions, c.Type)
			}
		}
		return nil
	}
	return r.HandleExternalResources()

}

func (r *ReconcileRequest) Update() error {
	if r.orig != nil && !reflect.DeepEqual(r.instance.Status, r.orig.Status) {
		diff := deep.Equal(&r.instance.Status, &r.orig.Status)
		r.Info("status of hosted zone changed", "diff", diff)
		if err := r.reconciler.DataPlane.Status().Update(r, r.instance); err != nil {
			return fmt.Errorf("failed to update changed status: %w", err)
		}
		r.TriggerChildren()
	} else {
		if r.orig == nil || !r.orig.GetDeletionTimestamp().IsZero() {
			r.TriggerChildren()
		}
	}
	return nil
}

func (r *ReconcileRequest) ApplyData(octx clusterutils.OperationContext, data []byte) (*unstructured.Unstructured, error) {
	o, err := clusterutils.ClientSideApply(r.reconciler.Runtime, octx, data)
	if err != nil {
		meta.SetStatusCondition(&r.instance.Status.Conditions, metav1.Condition{
			Type:    corednsv1alpha1.RuntimeConditionType,
			Reason:  corednsv1alpha1.ReasonUpdateFailed,
			Status:  metav1.ConditionFalse,
			Message: fmt.Sprintf("%s: %s", client.ObjectKeyFromObject(o), err.Error()),
		})
		return o, err
	}
	return o, err
}

func (r *ReconcileRequest) HandleExternalResources() error {

	err := r.reconciler.Mode.Prepare(r.ReconcileContext)
	if err != nil {
		return err
	}

	values, repeat := r.Values(r.reconciler.Mode)

	if repeat != nil {
		r.Info("valzues not yet complete: {{reason}}", "reason", repeat.Error())
	}
	// even if access for credentials has been failed, the dataplane is applied.
	// this may create a secret required to get the access token.

	r.Info("updating dataplane")
	dataplane, runtime, err := render.Render(r.reconciler.Manifests, values)
	if err != nil {
		return err
	}

	for _, data := range dataplane {
		_, err := clusterutils.ClientSideApply(r.reconciler.DataPlane, r, data)
		if err != nil {
			return err
		}
	}

	// if credential access failed, retry the reconcilation
	if repeat != nil {
		r.Info("dataplane still pending: {{reason}} -> requeue", "reason", repeat.Error())
		return nil // tre-rigger by watch
	}

	if true {
		dnsctx := DNSContext{
			ReconcileRequest: r,
		}

		var deplName client.ObjectKey
		var svcName client.ObjectKey

		r.Logger.Info("updating runtime")
		octx := clusterutils.WithModification(r,
			// set owners
			owner.AddOwnerModifier(r.reconciler.runtimeOwner, r.instance),
			// adapt to provide DNS records for nameservers
			func(obj client.Object) error { return r.reconciler.Options.DNSHandler.Modify(&dnsctx, obj) },
		)

		// apply standard manifests
		for _, data := range runtime {
			o, err := r.ApplyData(octx, data)
			if err != nil {
				return err
			}
			gvk := o.GetObjectKind().GroupVersionKind()
			if gvk.Kind == "Deployment" && gvk.Group == "apps" {
				deplName.Name = o.GetName()
				deplName.Namespace = o.GetNamespace()
			}
			if gvk.Kind == "Service" && (gvk.Group == "core" || gvk.Group == "") {
				var tmp corev1.Service
				svcName.Name = o.GetName()
				svcName.Namespace = o.GetNamespace()
				if err := r.reconciler.Runtime.Get(r, svcName, &tmp); err == nil {
					dnsctx.Service = &tmp
				} else {
					if !errors.IsNotFound(err) {
						err = fmt.Errorf("failing to read service %q; %w", client.ObjectKeyFromObject(o), err)
						meta.SetStatusCondition(&r.instance.Status.Conditions, metav1.Condition{
							Type:               corednsv1alpha1.RuntimeConditionType,
							Reason:             corednsv1alpha1.ReasonUpdateFailed,
							Status:             metav1.ConditionFalse,
							Message:            err.Error(),
							ObservedGeneration: r.instance.Generation,
						})
						return err
					}
				}
			}
		}

		// apply additional resources required by DNS provisioning for name servers
		for _, data := range r.reconciler.Options.DNSHandler.Manifests(&dnsctx, values) {
			_, err := r.ApplyData(octx, data)
			if err != nil {
				return err
			}
		}

		var sum error
		var deployment appsv1.Deployment

		if err := r.reconciler.Runtime.Get(r, deplName, &deployment); err == nil {
			ok, err := isDeploymentReady(&deployment)
			r.Info("deployment state", "deployment", deplName, "ready", ok, "error", err)
			msg := "Deployment serving requests"
			reason := corednsv1alpha1.ReasonRuntimeAvailable
			if !ok {
				reason = corednsv1alpha1.ReasonRuntimeUnavailable
			}
			if err != nil {
				msg = err.Error()
				if ok {
					reason = corednsv1alpha1.ReasonRuntimeDeploying
				}
			}
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.RuntimeConditionType,
				Reason:  reason,
				Message: msg,
				Status:  ConditionStatus(ok),
			})
		} else {
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.RuntimeConditionType,
				Reason:  corednsv1alpha1.ReasonRuntimeUnavailable,
				Message: err.Error(),
				Status:  metav1.ConditionFalse,
			})
			sum = errors2.Join(sum, err)
		}

		if dnsctx.Service != nil {
			cnames, err := r.reconciler.Options.DNSHandler.GetCNames(&dnsctx)
			r.Info("cnames state", "service", svcName, "cnames", cnames, "error", err)
			reason := corednsv1alpha1.ReasonNameserverPending
			msg := "waiting for external access to be provisioned"
			ok := false
			if err != nil {
				msg = err.Error()
			} else {
				if len(cnames) > 0 {
					r.instance.Status.NameServers = cnames
					reason = corednsv1alpha1.ReasonNameserverAvailable
					msg = "nameserver access ready"
					ok = true
				} else {
					msg = "nameserver access still pending"
				}
			}
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.NameserverConditionType,
				Reason:  reason,
				Message: msg,
				Status:  ConditionStatus(ok),
			})
		} else {
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.NameserverConditionType,
				Reason:  corednsv1alpha1.ReasonRuntimeUnavailable,
				Message: "no Service for DNS server found",
				Status:  metav1.ConditionFalse,
			})
			sum = errors2.Join(sum, err)
		}

		// calculate status summary.

		status := "Failed"
		msg := "status unknown"
		c := meta.FindStatusCondition(r.instance.Status.Conditions, corednsv1alpha1.ValidationConditionType)
		if c != nil {
			msg = c.Message
			if c.Status == metav1.ConditionTrue {
				c = meta.FindStatusCondition(r.instance.Status.Conditions, corednsv1alpha1.RuntimeConditionType)
				if c != nil {
					msg = c.Message
					if c.Status == metav1.ConditionTrue {
						c = meta.FindStatusCondition(r.instance.Status.Conditions, corednsv1alpha1.NameserverConditionType)
						if c != nil {
							msg = c.Message
							if c.Status == metav1.ConditionTrue {
								c = meta.FindStatusCondition(r.instance.Status.Conditions, corednsv1alpha1.ServerConditionType)
								if c != nil {
									msg = c.Message
									if c.Status == metav1.ConditionTrue {
										status = "Ready"
									}
								}
							}
						}
					}
				}
			}
		}
		r.instance.Status.Message = msg
		r.instance.Status.State = status
		return sum

	} else {
		r.Logger.Info("skipping runtime deployment")
	}

	return nil
}

func (r *ReconcileRequest) Delete(target string, clt client.Client, manifest []byte) error {
	obj := unstructured.Unstructured{}
	dec := yaml.NewDecodingSerializer(unstructured.UnstructuredJSONScheme)
	_, _, err := dec.Decode(manifest, nil, &obj)
	if err != nil {
		return err
	}

	current := unstructured.Unstructured{}
	current.SetGroupVersionKind(obj.GroupVersionKind())
	key := client.ObjectKey{
		Namespace: obj.GetNamespace(),
		Name:      obj.GetName(),
	}
	err = clt.Get(r, key, &current)

	if err != nil {
		if errors.IsNotFound(err) {
			return nil
		}
		return err
	}
	if !current.GetDeletionTimestamp().IsZero() {
		return fmt.Errorf("resource %q is still being deleted", key)
	}
	r.Info("deleting object", "name", key.Name, "namespace", key.Namespace, "target", target, "groupkind", obj.GroupVersionKind())
	err = clt.Delete(r, &obj)
	return err
}

func (r *ReconcileRequest) TriggerChildren() {
	r.reconciler.TriggerChildren(r, r.Logger, client.ObjectKeyFromObject(r.instance))
}

func (r *ReconcileRequest) SetStatusCondition(condition metav1.Condition) bool {
	if condition.ObservedGeneration == 0 {
		condition.ObservedGeneration = r.instance.Generation
	}
	return meta.SetStatusCondition(&r.instance.Status.Conditions, condition)
}

func GetAccessValues(in map[string]interface{}) map[string]interface{} {
	d := in["dataplane"].(map[string]interface{})

	t := d["token"]
	c := d["cdata"]
	if t != nil && c != nil {
		return map[string]interface{}{
			"token": t,
			"cdata": c,
		}
	}
	return nil
}

func isLoadBalancerReady(svc *corev1.Service) ([]net.IP, []string) {
	// 1. Check if the Service is actually a LoadBalancer type
	if svc.Spec.Type != corev1.ServiceTypeLoadBalancer {
		return nil, nil
	}

	// 2. Check the status field
	// If the slice is empty, the cloud provider hasn't finished yet
	ingress := svc.Status.LoadBalancer.Ingress
	if len(ingress) == 0 {
		return nil, nil
	}

	// 3. Ensure at least one entry has an IP or Hostname
	var ips []net.IP
	var cnames []string
	for _, i := range ingress {
		if i.IP != "" {
			ip := net.ParseIP(i.IP)
			if len(ip) == 0 {
				ips = append(ips, ip)
			}

		}
		if i.Hostname != "" {
			cnames = append(cnames, i.Hostname)
		}
	}

	return ips, cnames
}

func isDeploymentReady(deploy *appsv1.Deployment) (bool, error) {
	var err error

	prog := false
	avail := false

	for _, cond := range deploy.Status.Conditions {
		// Progressing = False usually means the deadline exceeded (failed)
		if cond.Type == appsv1.DeploymentProgressing {
			prog = true
			if cond.Status == corev1.ConditionFalse {
				err = fmt.Errorf("progressing: %s", cond.Message)
			}
		}
		// Available = False means the minimum required pods aren't up
		if cond.Type == appsv1.DeploymentAvailable {
			avail = true
			if cond.Status == corev1.ConditionFalse {
				err = fmt.Errorf("unavailable: %s", cond.Message)
			}
		}
	}

	_ = prog
	if !avail && err == nil {
		err = fmt.Errorf("deployment not yet ready")
	}
	if deploy.Status.ReadyReplicas > 0 {
		return true, err
	}
	return false, err
}
