package hostedzone

import (
	"fmt"
	"net"
	"reflect"
	"strings"

	"github.com/go-test/deep"
	"github.com/mandelsoft/goutils/general"
	"github.com/mandelsoft/kubecrtutils/cluster"
	. "github.com/mandelsoft/kubecrtutils/controller/controllerutils/reconcile"
	"github.com/mandelsoft/kubecrtutils/controller/controllerutils/reconciler"
	"github.com/mandelsoft/kubecrtutils/owner"
	corednsv1alpha1 "github.com/mandelsoft/kubedns/api/coredns/v1alpha1"
	"github.com/mandelsoft/kubedns/pkg/render"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/serializer/yaml"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
)

const GENERATED = "!!! DO NOT CHANGE MANUALLY, THIS OBJECT IS AUTOMATICALLY GENERATED BY THE HostedZOne CONTROLLER."

type Responsibility struct {
	Root       *corednsv1alpha1.HostedZone
	Parent     *corednsv1alpha1.HostedZone
	RuntimeSet bool
	Runtime    string
	Class      string
}

type ReconcileRequest struct {
	reconciler.DefaultReconcileRequest[*corednsv1alpha1.HostedZone, *HostedZoneReconciler]
}

var _ cluster.OperationContext = (*ReconcileRequest)(nil)

func (r *ReconcileRequest) UpdateStatus() Problem {
	p := r.DefaultReconcileRequest.UpdateStatus()
	if p == nil {
		r.TriggerChildren()
		r.TriggerEntries()
	}
	return p
}

func (r *ReconcileRequest) ReconcileDeleted() Problem {
	r.Info("Deleted hostedzone")
	r.TriggerEntries()
	return r.delete()
}

func (r *ReconcileRequest) Reconcile() Problem {
	obj := r.Object

	// anonymous validation for responsibility fields
	if !IsASCIIAlnumString(String(obj.Spec.Runtime, "")) || !IsASCIIAlnumString(String(obj.Spec.Class, "")) {
		r.SetStatusCondition(metav1.Condition{
			Type:               corednsv1alpha1.ValidationConditionType,
			Status:             metav1.ConditionFalse, // Use metav1 constant
			Reason:             corednsv1alpha1.ReasonInvalidParent,
			Message:            "class and runtime must use ASCII alphanumeric characters, only.",
			ObservedGeneration: obj.Generation,
		})
		return nil
	}

	// check responsibility
	ok, root, prob := r.IsResponsibile()
	if !ok || prob != nil {
		if !ok {
			r.Info("not responsible for this zone")
		}
		return prob
	}
	r.Info("have to handle object")

	if r.ChangedResponsibility() {
		// Handle Deletion
		r.Eventf(obj, corev1.EventTypeNormal, "ResponsibilityChanged", "Deleting because of responsibility change")
		r.Info("responsibility changed", "parent", obj.Spec.ParentRef, "runtime", obj.Spec.Runtime, "class", obj.Spec.Class)
		return r.delete()
	}

	// prepare finalizer update
	patch := client.MergeFrom(r.GetOrig())

	r.Info("found status", "status", obj.Status)

	// handle finalizer
	if obj.Spec.ParentRef != "" {
		// Remove finalizer from slave and update
		if controllerutil.RemoveFinalizer(obj, r.Reconciler.Finalizer) {
			r.Info("removing finalizer for slave zone")
			if err := r.Patch(r, obj, patch); err != nil {
				return TemporaryProblem(client.IgnoreNotFound(err))
			}
		}
	} else {
		if controllerutil.AddFinalizer(obj, r.Reconciler.Finalizer) {
			if err := r.Patch(r, obj, patch); err != nil {
				return TemporaryProblem(client.IgnoreNotFound(err))
			}
			r.Info("taking responsibility")
		}
	}

	//  Normal Business Logic
	r.Info("handle hosted zone")
	return r.handleObject(root)
}

func (r *ReconcileRequest) ReconcileDeleting() Problem {
	// Handle Deletion
	r.Eventf(r.Object, corev1.EventTypeNormal, "Deleting", "Deleting hosted zone")
	r.Info("deletion of object requested")
	return r.delete()
}

func (r *ReconcileRequest) delete() Problem {
	obj := r.Object
	if obj == nil || controllerutil.ContainsFinalizer(obj, r.Reconciler.Finalizer) {
		if obj == nil {
			r.Info("object vanished -> cleanup pending resources")
		} else {
			r.Info("already active -> delete dependent resources")
		}
		// Run your external cleanup logic here
		if prob := r.DeleteExternalResources(); prob != nil {
			// If cleanup fails, we don't remove the finalizer;
			// we requeue to try again.
			r.Info("error deleting external resources", "error", prob.String())
			return prob
		}

		if obj != nil {
			// Remove finalizer and update
			if controllerutil.RemoveFinalizer(obj, r.Reconciler.Finalizer) {
				patch := client.MergeFrom(r.GetOrig())

				r.Info("finally removing finalizer")
				if err := r.Patch(r, obj, patch); err != nil {
					return TemporaryProblem(client.IgnoreNotFound(err))
				}
			} else {
				r.Info("finalizer already gone")
			}
		}
	}

	// Stop reconciliation as the item is being deleted
	return nil
}

func (r *ReconcileRequest) GetFieldManager() string {
	return r.Reconciler.FieldManager
}

func (r *ReconcileRequest) Modify(cluster cluster.Cluster, obj client.Object) error {
	// no standard modification of resources by reconcile context
	return nil
}

func (r *ReconcileRequest) ChangedResponsibility() bool {
	obj := r.Object
	if obj == nil {
		// enforced object deletion
		return true
	}
	if !controllerutil.ContainsFinalizer(obj, r.Reconciler.Finalizer) {
		return false
	}
	if obj.Spec.ParentRef != "" {
		// zone has been moved and is no top-level zone anymore
		return true
	}
	if obj.Status.Observed == nil {
		// never handled
		return false
	}
	if obj.Status.Observed.Runtime != String(obj.Spec.Runtime, "") || obj.Status.Observed.Class != String(obj.Spec.Class, "") {
		// responsibility change has been requested
		return true
	}
	return false
}

func (r *ReconcileRequest) IsResponsibile() (bool, *Responsibility, Problem) {
	obj := r.Object
	if obj == nil {
		return true, nil, nil
	}
	force := false
	if controllerutil.ContainsFinalizer(obj, r.Reconciler.Finalizer) {
		force = true
	}
	info, ok, prob := r.Reconciler.GetRootInfo(r, r, obj)
	if prob != nil && prob.Error() != nil { // no incomplete state
		r.Info("lookup root with problem {{problem}}", "problem", prob)
		if prob.Requeue() {
			return false, nil, prob
		}
		if ok {
			// dangling object, always report problem
			r.Info("report zone problem", "error", prob.Error())
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.ValidationConditionType,
				Status:  metav1.ConditionFalse, // Use metav1 constant
				Reason:  corednsv1alpha1.ReasonInvalidParent,
				Message: prob.Error().Error(),
			})
			prob = nil
		}
		return false, nil, prob
	}
	r.Info("root '{{root}}', runtime '{{runtime}}', class '{{class}}'", "root", info.Root.Name, "runtime", info.Runtime, "class", info.Class)

	if force {
		return true, info, nil

	}
	new := info.Runtime == r.Reconciler.Options.Runtime && info.Class == r.Reconciler.Options.Class
	r.Info("checking match: {{match}}", "match", new)
	if info.Root.Status.Observed == nil {
		return new, info, nil
	}

	match := info.Root.Status.Observed.Class == r.Reconciler.Options.Class && info.Root.Status.Observed.Runtime == r.Reconciler.Options.Runtime
	r.Info("checking registered match for class {{observed}}: {{match}}", "match", new, "observed", info.Root.Status.Observed.Class)
	return match, info, nil

}

func (r *ReconcileRequest) handleObject(root *Responsibility) Problem {
	reason, err := r.Validate(root)
	if err != nil {
		if reason != "" {
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.ValidationConditionType,
				Status:  metav1.ConditionFalse, // Use metav1 constant
				Reason:  reason,
				Message: err.Error(),
			})
		}
		return Failed(err)
	}

	var observed *corednsv1alpha1.Observed
	if r.Object.Spec.ParentRef == "" {
		observed = r.Object.Status.Observed
		if observed == nil {
			r.Info("registering responsibility")
			observed = &corednsv1alpha1.Observed{
				Runtime: r.Reconciler.Options.Runtime,
				Class:   r.Reconciler.Options.Class,
			}
		}
	}

	r.Info("validation succeeded")
	// --- Validation Succeeded: Use meta.SetStatusCondition to set ConditionTrue ---
	r.SetStatusCondition(metav1.Condition{
		Type:    corednsv1alpha1.ValidationConditionType,
		Status:  metav1.ConditionTrue,
		Reason:  reason,
		Message: "The HostedZone specification passed all validation checks.",
	})
	SetPointerField(&r.Object.Status.Observed, observed)

	if r.Object.Spec.ParentRef != "" {
		// update status from root
		r.transferConditions(client.ObjectKeyFromObject(root.Root), root.Root.Status.Conditions)
		return nil
	}
	return r.HandleExternalResources()

}

func (r *ReconcileRequest) UpdateObject() error {
	if r.Orig != nil && !reflect.DeepEqual(r.Object.Status, r.Orig.Status) {
		diff := deep.Equal(&r.Object.Status, &r.Orig.Status)
		r.Info("status of hosted zone changed", "diff", diff)
		if err := r.Status().Update(r, r.Object); err != nil {
			return fmt.Errorf("failed to update changed status: %w", err)
		}
		r.TriggerChildren()
		r.TriggerEntries()
	} else {
		if r.Orig == nil || !r.Orig.GetDeletionTimestamp().IsZero() {
			r.TriggerChildren()
			r.TriggerEntries()
		}
	}
	return nil
}

func (r *ReconcileRequest) ApplyData(octx cluster.OperationContext, data []byte, mod ...*cluster.ModificationInfo) (*unstructured.Unstructured, error) {
	o, err := cluster.ClientSideApply(r.Reconciler.Runtime, octx, data, mod...)
	if err != nil {
		meta.SetStatusCondition(&r.Object.Status.Conditions, metav1.Condition{
			Type:    corednsv1alpha1.RuntimeConditionType,
			Reason:  corednsv1alpha1.ReasonUpdateFailed,
			Status:  metav1.ConditionFalse,
			Message: fmt.Sprintf("%s: %s", client.ObjectKeyFromObject(o), err.Error()),
		})
		return o, err
	}
	return o, err
}

func (r *ReconcileRequest) HandleExternalResources() Problem {

	prob := r.Reconciler.Mode.Prepare(r)
	if prob != nil {
		return prob
	}

	url, err := r.GetAPIServerURL()
	if err != nil {
		return Failed(fmt.Errorf("cannot determine api server URL: %w", err))
	}

	r.Info("using api server URL: {{url}}", "url", url)
	values, repeat := r.Values(r.Reconciler.Mode, false)

	if repeat != nil {
		r.Info("values not yet complete: {{reason}}", "reason", repeat.Error())
	}
	// even if access for credentials has been failed, the dataplane is applied.
	// this may create a secret required to get the access token.

	dataplane, runtime, err := render.Render(r.Reconciler.Manifests, values)
	if err != nil {
		return Failedf("error rendering manifests: %s", err.Error())
	}

	r.Info("updating dataplane")

	var modified cluster.ModificationInfo
	for _, data := range dataplane {
		_, err := cluster.ClientSideApply(r.Cluster, r, data, &modified)
		if err != nil {
			return TemporaryProblemf("error deploying dataplane: %s", err.Error())
		}
	}
	modified.Report(r, "Dataplane", r.Object)

	// if credential access failed, retry the reconcilation
	if repeat != nil {
		r.Info("dataplane still pending: {{reason}} -> requeue", "reason", repeat.Error())
		r.Eventf(r.Object, corev1.EventTypeNormal, "DataplanePending", "Dataplane still pending")

		return nil // re-rigger by watch
	}

	if true {
		dnsctx := DNSContext{
			ReconcileRequest: r,
		}

		var deplName client.ObjectKey
		var svcName client.ObjectKey

		r.Info("updating runtime")
		octx := cluster.WithModification(r,
			// set owners
			owner.AddOwnerModifier(r, r.Object, r.Reconciler.ownerFilter, r.GetController().GetOwnerHandler()),
			// adapt to provide DNS records for nameservers
			cluster.ObjectModifierFunc(func(_ cluster.Cluster, obj client.Object) error {
				return r.Reconciler.Options.DNSHandler.Modify(&dnsctx, obj)
			}),
		)

		// apply standard manifests
		modified.Clear()
		for _, data := range runtime {
			o, err := r.ApplyData(octx, data, &modified)
			if err != nil {
				if checkNotModifiableError(err) {
					r.DeleteManifest(data, r.Reconciler.Runtime)
				}
				return TemporaryProblemf("error deploying runtime: %s", err.Error())
			}
			gvk := o.GetObjectKind().GroupVersionKind()
			if gvk.Kind == "Deployment" && gvk.Group == "apps" {
				deplName.Name = o.GetName()
				deplName.Namespace = o.GetNamespace()
			}
			if gvk.Kind == "Service" && (gvk.Group == "core" || gvk.Group == "") {
				var tmp corev1.Service
				svcName.Name = o.GetName()
				svcName.Namespace = o.GetNamespace()
				if err := r.Reconciler.Runtime.Get(r, svcName, &tmp); err == nil {
					dnsctx.Service = &tmp
				} else {
					if !errors.IsNotFound(err) {
						return TemporaryProblem(err)
					}
				}
			}
		}
		modified.Report(r, "Runtime", r.Object)

		// apply additional resources required by DNS provisioning for name servers
		modified.Clear()

		dnsdataplane, dnsruntime, prob := r.Reconciler.Options.DNSHandler.Manifests(&dnsctx, values)
		if prob != nil {
			return prob
		}
		if len(dnsdataplane) > 0 {
			r.Info("found {{amount}} dns dataplane manifests", "amount", len(dnsdataplane))
			for _, data := range dnsdataplane {
				_, err := cluster.ClientSideApply(r.Cluster, r, data, &modified)
				if err != nil {
					return TemporaryProblemf("error deploying nameserver dns dataplane: %s", err.Error())
				}
			}
		}
		if len(dnsruntime) > 0 {
			r.Info("found {{amount}} dns runtime manifests", "amount", len(dnsdataplane))
			for _, data := range dnsruntime {
				_, err := r.ApplyData(octx, data, &modified)
				if err != nil {
					return TemporaryProblemf("error deploying nameserver dns runtime: %s", err.Error())
				}
			}
		}
		modified.Report(r, "DNSExtensions", r.Object)
		modified.Clear()

		var sum Problem
		var deployment appsv1.Deployment

		if err := r.Reconciler.Runtime.Get(r, deplName, &deployment); err == nil {
			ok, prob := isDeploymentReady(&deployment)
			r.Info("deployment state", "deployment", deplName, "ready", ok, "error", err)
			msg := "Deployment serving requests"
			reason := corednsv1alpha1.ReasonRuntimeAvailable
			if !ok {
				reason = corednsv1alpha1.ReasonRuntimeUnavailable
			}
			if prob != nil {
				msg = prob.Message()
				if ok {
					reason = corednsv1alpha1.ReasonRuntimeDeploying
				}
				r.Eventf(r.Object, corev1.EventTypeNormal, "Pending", "DNS server deployment still pending")
			}
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.RuntimeConditionType,
				Reason:  reason,
				Message: msg,
				Status:  ConditionStatus(ok),
			})
		} else {
			if errors.IsNotFound(err) {
				r.SetStatusCondition(metav1.Condition{
					Type:    corednsv1alpha1.RuntimeConditionType,
					Reason:  corednsv1alpha1.ReasonRuntimeUnavailable,
					Message: err.Error(),
					Status:  metav1.ConditionFalse,
				})
			}
			sum = AggregateProblem(sum, TemporaryProblem(err))
		}

		var cnames []string
		if dnsctx.Service != nil {
			cnames, prob = r.Reconciler.Options.DNSHandler.GetCNames(&dnsctx)
			sum = AggregateProblem(sum, prob)
			r.Info("cnames state", "service", svcName, "cnames", cnames, "error", err)
			reason := corednsv1alpha1.ReasonNameserverPending
			msg := "waiting for external access to be provisioned"
			ok := false
			if prob != nil {
				msg = prob.Message()
			} else {
				if len(cnames) > 0 {
					r.Object.Status.NameServers = cnames
					reason = corednsv1alpha1.ReasonNameserverAvailable
					msg = "nameserver access ready"
					ok = true
				} else {
					msg = "nameserver access still pending"
					r.Eventf(r.Object, corev1.EventTypeNormal, "Pending", "nameserver access still pending")
				}
			}
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.NameserverConditionType,
				Reason:  reason,
				Message: msg,
				Status:  ConditionStatus(ok),
			})
		} else {
			r.SetStatusCondition(metav1.Condition{
				Type:    corednsv1alpha1.NameserverConditionType,
				Reason:  corednsv1alpha1.ReasonRuntimeUnavailable,
				Message: "no Service for DNS server found",
				Status:  metav1.ConditionFalse,
			})
			sum = AggregateProblem(sum, Requeuef("service not found"))
		}

		// calculate status summary.
		r.summary()
		return sum

	} else {
		r.Info("skipping runtime deployment")
	}

	return nil
}

func (r *ReconcileRequest) DeleteManifest(manifest []byte, cluster ...cluster.Cluster) Problem {
	obj := unstructured.Unstructured{}
	dec := yaml.NewDecodingSerializer(unstructured.UnstructuredJSONScheme)
	_, _, err := dec.Decode(manifest, nil, &obj)
	if err != nil {
		return Failedf("error decoding manifest: %s", err.Error())
	}

	current := unstructured.Unstructured{}
	current.SetGroupVersionKind(obj.GroupVersionKind())
	key := client.ObjectKey{
		Namespace: obj.GetNamespace(),
		Name:      obj.GetName(),
	}
	cl := general.OptionalDefaulted(r.Cluster, cluster...)
	err = cl.Get(r, key, &current)

	if err != nil {
		if errors.IsNotFound(err) {
			r.Info("object {{kind}} {{key}} already gone", "kind", obj.GroupVersionKind().GroupKind(), "key", key, "target", cl.GetName())
			return nil
		}
		return TemporaryProblemf("error getting object %s from %s: %s", key, cl.GetName(), err.Error())
	}
	if !current.GetDeletionTimestamp().IsZero() {
		return Requeuef("resource %q is still being deleted", key)
	}
	r.Info("deleting object {{kind}} {{key}}", "kind", obj.GroupVersionKind().GroupKind(), "key", key, "target", cl.GetName())
	err = cl.Delete(r, &obj)
	if errors.IsNotFound(err) {
		return nil
	}
	return TemporaryProblem(err)
}

func (r *ReconcileRequest) TriggerChildren() {
	r.Reconciler.TriggerChildren(r, r, r.GetKey())
}

func (r *ReconcileRequest) TriggerEntries() {
	r.Reconciler.TriggerEntries(r, r, r.GetKey())
}

func (r *ReconcileRequest) SetStatusCondition(condition metav1.Condition) bool {
	if condition.ObservedGeneration == 0 {
		condition.ObservedGeneration = r.Object.Generation
	}
	m := meta.SetStatusCondition(&r.Object.Status.Conditions, condition)
	if m {
		r.Eventf(r.Object, corev1.EventTypeNormal, condition.Type, condition.Message)
	}
	return m
}

func GetAccessValues(in map[string]interface{}) map[string]interface{} {
	d := in["dataplane"].(map[string]interface{})

	t := d["token"]
	c := d["cdata"]
	if t != nil && c != nil {
		return map[string]interface{}{
			"token": t,
			"cdata": c,
		}
	}
	return nil
}

func isLoadBalancerReady(svc *corev1.Service) ([]net.IP, []string) {
	// 1. Check if the Service is actually a LoadBalancer type
	if svc.Spec.Type != corev1.ServiceTypeLoadBalancer {
		return nil, nil
	}

	// 2. Check the status field
	// If the slice is empty, the cloud provider hasn't finished yet
	ingress := svc.Status.LoadBalancer.Ingress
	if len(ingress) == 0 {
		return nil, nil
	}

	// 3. Ensure at least one entry has an IP or Hostname
	var ips []net.IP
	var cnames []string
	for _, i := range ingress {
		if i.IP != "" {
			ip := net.ParseIP(i.IP)
			if len(ip) == 0 {
				ips = append(ips, ip)
			}

		}
		if i.Hostname != "" {
			cnames = append(cnames, i.Hostname)
		}
	}

	return ips, cnames
}

func isDeploymentReady(deploy *appsv1.Deployment) (bool, Problem) {
	var prob Problem

	prog := false
	avail := false

	for _, cond := range deploy.Status.Conditions {
		// Progressing = False usually means the deadline exceeded (failed)
		if cond.Type == appsv1.DeploymentProgressing {
			prog = true
			if cond.Status == corev1.ConditionFalse {
				prob = WatchBackedProblemf("no progress: %s", cond.Message)
			} else {
				if !avail {
					prob = WatchBackedProblemf("progressing: %s", cond.Message)
				}
			}
		}
		// Available = False means the minimum required pods aren't up
		if cond.Type == appsv1.DeploymentAvailable {
			avail = true
			if cond.Status == corev1.ConditionFalse {
				if prob == nil {
					prob = WatchBackedProblemf("unavailable: %s", cond.Message)
				}
			} else {
				prob = nil
			}
		}
	}

	_ = prog
	if !avail && prob == nil {
		prob = WatchBackedProblemf("deployment not yet ready")
	}
	if deploy.Status.ReadyReplicas > 0 {
		return true, prob
	}
	return false, prob
}

func checkNotModifiableError(err error) bool {
	if err != nil && errors.IsInvalid(err) {
		// This is a 422 Unprocessable Entity / Invalid error
		if strings.Contains(err.Error(), "may not change once set") {
			// Strategy: You likely need to delete and recreate the service
			// if the LoadBalancer class actually needs to change.
			return true
		}
	}
	return false
}

////////////////////////////////////////////////////////////////////////////////

// Reconcilecontext implementation

var _ ReconcileContext = (*ReconcileRequest)(nil)

func (r *ReconcileRequest) IsSimulate() bool {
	return false
}

func (r *ReconcileRequest) GetPlatform() string {
	return r.Reconciler.Options.Platform
}

func (r *ReconcileRequest) Values(m Mode, deleting bool) (map[string]interface{}, error) {
	return Values(r, m, deleting)
}
