kind: ConfigMap
apiVersion: v1
metadata:
  name: (( values.runtime.name ))
  namespace: (( values.runtime.namespace ))
  labels:
    target: runtime
    app: (( values.runtime.label ))
data:
  # The key name here ('Corefile') will be the filename in the volume mount
  Corefile: |
    .:53 {
      errors
      health
      ready
      cache 30
      kubedyndns . {
        mode Primary
        zoneobject (( values.dataplane.zone ))
        namespaces (( values.dataplane.namespace ))
        transitive
        slave
        (( (values.runtime.secret != "" ) ? "endpoint " values.dataplane.server  :"" ))
        (( (values.runtime.secret != "" ) ? "token /etc/coredns/access/token /etc/coredns/access/ca.crt" :"" ))
        ttl 30
      }
    }