apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: (( values.dataplane.name )) # Renamed the Role to reflect write access
  namespace: (( values.dataplane.namespace ))
  labels:
    target: dataplane
    app: (( values.dataplane.label ))
rules:
  # Granting FULL access to common networking and discovery resources
  - apiGroups: ["coredns.mandelsoft.org"] # Core API Group
    resources: ["HostedZones", "CoreDNSEntries"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    # A simpler way to grant all verbs is ["*"]