helper:
  <<<: (( &temporary ))
  secret:
    <<<: (( &template ))
    kind: Secret
    metadata:
      name: (( values.config.name ))
      namespace: (( values.runtime.namespace ))
      labels:
        target: runtime
        app: (( values.deployment.label ))
    type: Opaque
    stringData:
      token: (( values.dataplane.token ))
      ca.crt: (( values.dataplane.cadata ))
      # The key name here ('Corefile') will be the filename in the volume mount
      KubeConfig: |
        apiVersion: v1
        kind: Config
        preferences: {}
    
        # 1. Cluster Definition
        clusters:
        - cluster:
            # Use the CA_DATA retrieved above (base64 encoded)
            certificate-authority-data: (( values.dataplane.cadata ))
            server: (( values.dataplane.server ))
          name: api-cluster
    
        # 2. User Definition (Authentication)
        users:
        - name: dns-service-sa-user
          user:
            # Use the SA_TOKEN retrieved above (raw, not base64 encoded)
            token: (( values.dataplane.token ))
    
        # 3. Context Definition (Links Cluster and User)
        contexts:
        - context:
            cluster: api-cluster
            user: dns-service-sa-user
            namespace: (( values.dataplane.namespace )) # The namespace the service account operates in
          name: dns-sa-context
    
        # 4. Set the Current Context
        current-context: dns-sa-context

manifests:
  # secret only require in separated mode, otherwise in-cluster access is used.
  secret:  (( optional(values.runtime.separated, *helper.secret) ))