helper:
  <<<: (( &temporary ))
  kubeconfig: |
    apiVersion: v1
    kind: Config
    preferences: {}
    
    # 1. Cluster Definition
    clusters:
    - cluster:
        # Use the CA_DATA retrieved above (base64 encoded)
        certificate-authority-data: (( values.dataplane.access.cadata ))
        server: (( values.dataplane.server ))
      name: api-cluster
    
    # 2. User Definition (Authentication)
    users:
    - name: dns-service-sa-user
      user:
        # Use the SA_TOKEN retrieved above (raw, not base64 encoded)
        token: (( values.dataplane.access.token ))
    
    # 3. Context Definition (Links Cluster and User)
    contexts:
    - context:
        cluster: api-cluster
        user: dns-service-sa-user
        namespace: (( values.dataplane.namespace )) # The namespace the service account operates in
      name: dns-sa-context
    
    # 4. Set the Current Context
    current-context: dns-sa-context

  secret:
    <<<: (( &template ))
    kind: Secret
    apiVersion: v1
    metadata:
      name: (( values.runtime.secret.name ))
      namespace: (( values.runtime.namespace ))
      labels:
        target: runtime
        app: (( values.runtime.label ))
    type: Opaque
    data:
      token: (( base64(values.dataplane.access.token) ))
      ca.crt: (( base64(values.dataplane.access.cadata) ))
      # The key name here ('Corefile') will be the filename in the volume mount
      KubeConfig: (( base64(helper.kubeconfig) ))

manifests:
  # secret only require in separated mode, otherwise in-cluster access is used.
  secret:  (( optional(values.runtime.secret.name != "", *helper.secret) ))