helper:
  <<<: (( &temporary ))
  iaas:
    aws:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      loadBalancerClass: service.k8s.aws/nlb

apiVersion: v1
kind: Service
metadata:
  name: (( values.runtime.name ))
  namespace: (( values.runtime.namespace ))

  labels:
    target: runtime
    app: (( values.runtime.label ))
  annotations: (( helper.iaas[values.runtime.platform].annotations || ~~ ))

spec:
  type: LoadBalancer
  loadBalancerClass: (( helper.iaas[values.runtime.platform].loadBalancerClass || ~~ ))

  # Selects the pods created by the Deployment
  selector:
    app: (( values.runtime.label ))

  ports:
    - name: dns-udp-port
      protocol: UDP
      port: 53          # The port the Service exposes
      targetPort: 53    # The containerPort defined in the Deployment